<a href="https://colab.research.google.com/github/osh9149/2025_DataScience/blob/main/Pandas(loc%2C_iloc).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
f = files.upload()

Saving korea_univ.xlsx to korea_univ.xlsx

In [22]:
df=pd.read_excel('korea_univ.xlsx')
df

,기준연도,학교종류,설립구분,지역,상태,학교,수업료,등록금,인문사회,자연과학,예체능,공학,의학,도로명주소,위도,경도
0,2025,대학교,사립,경남,기존,가야대학교(김해),7239309.3,7239309.3,6359893.9,7534000.0,0.0,0.0,0.0,경상남도 김해시 삼계로 208,35.269816,128.872321
1,2025,대학교,사립,경기,기존,가천대학교,8812617.8,8812617.8,7576022.8,8805371.2,9622089.6,9562567.8,10374000.0,경기도 성남시 수정구 성남대로 1342,37.451235,127.129394
2,2025,대학교,사립,강원,기존,가톨릭관동대학교,7505368.9,7505368.9,6595136.5,7998357.9,8522435.7,8549265.1,10390000.0,강원특별자치도 강릉시 범일로579번길 24,37.737329,128.873705
3,2025,대학교,사립,충북,기존,가톨릭꽃동네대학교,7506277.8,7506277.8,6655500.0,7833500.0,0.0,0.0,0.0,충청북도 청주시 서원구 현도면 상삼길 133,36.521973,127.402985
4,2025,대학교,사립,경기,기존,가톨릭대학교,7493634.7,7493634.7,6435650.1,7813473.6,9004000.0,8719758.6,0.0,경기도 부천시 원미구 지봉로 43,37.487531,126.798602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,2025,대학교,사립,충남,기존,호서대학교,8164909.4,8164909.4,7168131.9,8280456.5,8682813.3,8665180.7,0.0,충청남도 아산시 배방읍 호서로79번길 20,36.734463,127.077107
209,2025,산업대학,사립,전북,기존,호원대학교,7269319.6,7269319.6,6010206.7,7462473.7,7750319.3,7178862.6,0.0,전북특별자치도 군산시 임피면 호원대3길 64,35.967926,126.863788
210,2025,대학교,사립,서울,기존,홍익대학교,8836668.5,8836668.5,7238597.1,7239800.0,9653790.7,9347585.5,0.0,서울특별시 마포구 와우산로 94,37.552519,126.924991
211,2025,대학교,사립,경기,기존,화성의과학대학교,7704138.4,7704138.4,7210792.8,8237894.7,7570907.8,0.0,0.0,경기도 화성시 남양읍 남양중앙로 400-5,37.202865,126.839628
212,2025,사이버대학(대학),사립,부산,기존,화신사이버대학교,2527107.2,2527107.2,2527107.2,0.0,0.0,0.0,0.0,부산광역시 연제구 고분로191번길 1,35.185746,129.103258

#데이터프레임의 특정 컬럼을 추출해오는 방법

In [23]:
df.index

RangeIndex(start=0, stop=213, step=1)

In [5]:
df['학교']

0      가야대학교(김해)
1          가천대학교
2       가톨릭관동대학교
3      가톨릭꽃동네대학교
4         가톨릭대학교
         ...
208        호서대학교
209        호원대학교
210        홍익대학교
211     화성의과학대학교
212     화신사이버대학교
Name: 학교, Length: 213, dtype: object

In [34]:
df['등록금'].idxmax()

147

In [35]:
df['등록금'].idxmin()

185

In [31]:
df1=df.sort_values(by=['등록금'], ascending=[False])
df1

,기준연도,학교종류,설립구분,지역,상태,학교,수업료,등록금,인문사회,자연과학,예체능,공학,의학,도로명주소,위도,경도
147,2025,대학교,사립,대전,기존,을지대학교,10969266.7,10969266.7,0.0,11158142.9,0.0,0.0,10804000.0,대전광역시 중구 계룡로771번길 77,36.333022,127.405572
173,2025,대학교,사립,서울,기존,추계예술대학교,9600692.0,9600692.0,7895238.1,0.0,10175256.7,0.0,0.0,서울특별시 서대문구 북아현로11가길 7,37.563177,126.954059
79,2025,대학교,사립,경기,기존,명지대학교,9592689.4,9592689.4,0.0,8712329.0,9958595.6,9668650.6,0.0,경기도 용인시 처인구 명지로 116,37.221807,127.190184
127,2025,대학교,사립,경기,기존,신한대학교,9525092.6,9525092.6,7840000.0,9500000.0,0.0,9980000.0,0.0,경기도 동두천시 벌마들로40번길 30,37.903862,127.037889
181,2025,대학교,사립,경기,기존,한국공학대학교,9450433.9,9450433.9,7943904.6,0.0,0.0,9614481.5,0.0,경기도 시흥시 산기대학로 237,37.339733,126.733539
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2025,사이버대학(대학),사립,서울,기존,서울디지털대학교,2274830.3,2274830.3,2273979.6,2257027.4,2273167.8,2282722.0,0.0,서울특별시 강서구 공항대로 424,37.555000,126.854020
30,2025,대학교,특별법법인,광주,기존,광주과학기술원,2060000.0,2060000.0,0.0,2060000.0,0.0,2060000.0,0.0,광주광역시 북구 첨단과기로 123,35.226879,126.842948
135,2025,대학교,사립,전남,기존,영산선학대학교,2000000.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,전라남도 영광군 백수읍 성지로 1357,35.327352,126.441340
163,2025,대학교,사립,경기,기존,중앙승가대학교,1820000.0,1820000.0,1820000.0,0.0,0.0,0.0,0.0,경기도 김포시 승가로 123,37.606935,126.708867
185,2025,방송통신대학,국립,서울,기존,한국방송통신대학교,761694.9,761694.9,730888.8,731600.0,757600.0,2214000.0,0.0,서울특별시 종로구 대학로 86,37.579195,127.003291

In [32]:
df1['등록금'].idxmax()

np.int64(147)

In [33]:
df1['등록금'].idxmin()

np.int64(185)

#loc(location) 데이터프레임의 특정 행이나 컬럼을 추출해오는 방법

In [6]:
#전체 데이터 프레임에서 인덱스이름이 '0'인행만 추출

df.loc[0]

기준연도                 2025
학교종류                  대학교
설립구분                   사립
지역                     경남
상태                     기존
학교              가야대학교(김해)
수업료             7239309.3
등록금             7239309.3
인문사회            6359893.9
자연과학            7534000.0
예체능                   0.0
공학                    0.0
의학                    0.0
도로명주소    경상남도 김해시 삼계로 208
위도              35.269816
경도             128.872321
Name: 0, dtype: object

In [8]:
df.loc[0,'학교']

'가야대학교(김해)'

In [9]:
df.loc[:,'학교']

0      가야대학교(김해)
1          가천대학교
2       가톨릭관동대학교
3      가톨릭꽃동네대학교
4         가톨릭대학교
         ...
208        호서대학교
209        호원대학교
210        홍익대학교
211     화성의과학대학교
212     화신사이버대학교
Name: 학교, Length: 213, dtype: object

In [10]:
df.loc[:10,'학교':'등록금']

           학교        수업료        등록금
0   가야대학교(김해)  7239309.3  7239309.3
1       가천대학교  8812617.8  8812617.8
2    가톨릭관동대학교  7505368.9  7505368.9
3   가톨릭꽃동네대학교  7506277.8  7506277.8
4      가톨릭대학교  7493634.7  7493634.7
5    감리교신학대학교  6820923.7  6820923.7
6       강남대학교  7968388.7  7968388.7
7       강서대학교  7924720.2  7924720.2
8       강원대학교  4179919.0  4179919.0
9       건국대학교  8748292.8  8748292.8
10      건양대학교  6625935.9  6625935.9

#iloc(interger location) 데이터프레임의 행이나 컬럼의 순서를 나타내는 정수로 특정 값을 추출해오는 방법

In [11]:
#전체 데이터 프레임에서 0번째 행에 있는 값들만 추출

df.iloc[0]

기준연도                 2025
학교종류                  대학교
설립구분                   사립
지역                     경남
상태                     기존
학교              가야대학교(김해)
수업료             7239309.3
등록금             7239309.3
인문사회            6359893.9
자연과학            7534000.0
예체능                   0.0
공학                    0.0
의학                    0.0
도로명주소    경상남도 김해시 삼계로 208
위도              35.269816
경도             128.872321
Name: 0, dtype: object

In [12]:
#df.iloc[행인덱스, 열인덱스]

df.iloc[0,2]

'사립'

In [13]:
df.iloc[:5, :5]

   기준연도 학교종류 설립구분  지역  상태
0  2025  대학교   사립  경남  기존
1  2025  대학교   사립  경기  기존
2  2025  대학교   사립  강원  기존
3  2025  대학교   사립  충북  기존
4  2025  대학교   사립  경기  기존

In [36]:
df2=df1.groupby('지역').count()
df2=df2.sort_values(by=['학교종류'], ascending=[False])
df2

    기준연도  학교종류  설립구분  상태  학교  수업료  등록금  인문사회  자연과학  예체능  공학  의학  도로명주소  위도  경도
지역
서울    51    51    51  51  51   51   51    51    51   51  51  51     51  51  51
경기    29    29    29  29  29   29   29    29    29   29  29  29     29  29  29
경북    17    17    17  17  17   17   17    17    17   17  17  17     17  17  17
충남    16    16    16  16  16   16   16    16    16   16  16  16     16  16  16
부산    16    16    16  16  16   16   16    16    16   16  16  16     16  16  16
충북    12    12    12  12  12   12   12    12    12   12  12  12     12  12  12
대전    12    12    12  12  12   12   12    12    12   12  12  12     12  12  12
전북    11    11    11  11  11   11   11    11    11   11  11  11     11  11  11
광주    11    11    11  11  11   11   11    11    11   11  11  11     11  11  11
전남     9     9     9   9   9    9    9     9     9    9   9   9      9   9   9
강원     8     8     8   8   8    8    8     8     8    8   8   8      8   8   8
경남     8     8     8   8   8    8    8     8     8    8   8   8      8   8   8
대구     4     4     4   4   4    4    4     4     4    4   4   4      4   4   4
인천     4     4     4   4   4    4    4     4     4    4   4   4      4   4   4
울산     2     2     2   2   2    2    2     2     2    2   2   2      2   2   2
제주     2     2     2   2   2    2    2     2     2    2   2   2      2   2   2
세종     1     1     1   1   1    1    1     1     1    1   1   1      1   1   1

In [37]:
df2.index

Index(['서울', '경기', '경북', '충남', '부산', '충북', '대전', '전북', '광주', '전남', '강원', '경남',
       '대구', '인천', '울산', '제주', '세종'],
      dtype='object', name='지역')

In [38]:
df2['학교']

지역
서울    51
경기    29
경북    17
충남    16
부산    16
충북    12
대전    12
전북    11
광주    11
전남     9
강원     8
경남     8
대구     4
인천     4
울산     2
제주     2
세종     1
Name: 학교, dtype: int64